name: Template UI
language: nodejs
variables:
  - name: bearer_token
    inputType: FreeText
    description: ''
    defaultValue: abc111
    required: false
  - name: Deployment__Id
    inputType: FreeText
    description: ''
    defaultValue: dep001
    required: false
  - name: offers_topic
    inputType: InputTopic
    description: ''
    defaultValue: special-offers
    required: false
  - name: click_topic
    inputType: InputTopic
    description: ''
    defaultValue: enriched-click-data
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
