name: Template UI
language: nodejs
variables:
  - name: bearer_token
    inputType: FreeText
    description: ''
    defaultValue: pat-087fb05b72df4e91b8eff7712e409965
    required: false
  - name: Deployment__Id
    inputType: FreeText
    description: ''
    defaultValue: 03c965bd-8f6a-40ec-97ae-e70fd974738e
    required: false
  - name: offers_topic
    inputType: InputTopic
    description: ''
    defaultValue: special-offers
    required: false
  - name: click_topic
    inputType: OutputTopic
    description: ''
    defaultValue: click-data
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
