name: Template UI
language: nodejs
variables:
  - name: bearer_token
    inputType: FreeText
    description: ''
    defaultValue: abc111
    required: false
  - name: Deployment__Id
    inputType: FreeText
    description: ''
    defaultValue: dep001
    required: false
dockerfile: build/dockerfile
defaultFile: src/app/services/quix.service.ts
