name: Streamlit
language: python
variables:
  - name: redis_host
    inputType: Secret
    description: ''
    defaultValue: redis_host
    required: false
  - name: redis_port
    inputType: Secret
    description: ''
    defaultValue: redis_port
    required: false
  - name: redis_password
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
