name: Detect User Behaviour
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic for enriched user data
    defaultValue: ''
    required: true
  - name: window_minutes
    inputType: FreeText
    description: Minutes for the rolling window to detect user behaviour
    defaultValue: 30
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: behaviour_detector.py
